### ISSUE TITLE
华为P9( Android 7)导入证书为系统级别证书后，访问 https 网站仍然出现证书警告

### ISSUE THREAD

**Issue by Lllly101** [Lllly101/CodeMore#2]
### 问题描述
华为P9（ 已 root ，安卓版本为7 ）安装 Burp 证书为`系统`信任证书后，浏览器访问百度首页或者其他 https 网站仍然会出现`证书警告`，且部分图片无法加载出来，能看到 https 流量。

### 已尝试的方案
1. 在新机-华为Mate 10（Android 8）上配置证书为`用户证书`
2. 多次重启

### 参考资料
1. [Configuring Burp Suite with Android Nougat](https://blog.ropnop.com/configuring-burp-suite-with-android-nougat/)
2. [17281202-intercepting-android-version-8-1-https-traffic](https://support.portswigger.net/customer/portal/questions/17281202-intercepting-android-version-8-1-https-traffic) Portswigger 官方回复和讨论
3. [Changes-to-trusted](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html)

### 解决思路
1. BurpSuite 重新生成证书导为用户证书，已在两台 Android 7 的华为手机上成功抓取 https 数据包。

### ChangeLog
- 190710 update
- 190709 init

**Comment by Lllly101** [comment]
场景：MacOS平台，执行 `fastboot flash recovery twrp.img` 执行后出现 `ERROR: Couldn't create a device interface iterator: (e00002bd)` 错误

解决：`MacOS Android Platform Tools` 版本太高，故而需要低版本的工具来解决。 [Android Platform Tools 26.0.1](https://dl.google.com/android/repository/platform-tools_r26.0.1-darwin.zip)

**Comment by c0rpse** [comment]
求大牛 root 金立GN5005！
